"""removed diplomat.name constraint

Revision ID: f3fdd3fce68e
Revises: 6eb77eae96f8
Create Date: 2018-09-28 22:16:25.438660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3fdd3fce68e'
down_revision = '6eb77eae96f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('diplomat_name_key', 'diplomat', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('diplomat_name_key', 'diplomat', ['name'])
    # ### end Alembic commands ###
