"""Adds key_name column

Revision ID: fde5de55e323
Revises: f3fdd3fce68e
Create Date: 2018-09-29 11:43:53.366031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde5de55e323'
down_revision = 'f3fdd3fce68e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diplomat', sa.Column('key_name', sa.String(length=256), nullable=False))
    op.create_unique_constraint(None, 'diplomat', ['key_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'diplomat', type_='unique')
    op.drop_column('diplomat', 'key_name')
    # ### end Alembic commands ###
